apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-mlops
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: retail-mlops
  template:
    metadata:
      labels:
        app: retail-mlops
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
